//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""Bolt_date"":"""",""Bolt_time"":"""",""TempUnits"":""C"",""WindSpeedUnits"":""K"",""Bolt_SkyTemp"":30,""Bolt_Temp"":10,""Bolt_SensorTemp"":10,""Bolt_WindSpeed"":2,""Bolt_Hum"":70,""Bolt_DewPoint"":-100,""Bolt_Heater"":30,""Bolt_RainFlag"":0,""Bolt_WetFlag"":0,""Bolt_SinceLastMeasure"":0,""Bolt_now"":0,""Bolt_CloudCond"":1,""Bolt_WindCond"":1,""Bolt_RainCond"":1,""Bolt_DaylighCond"":1,""Bolt_RoofCloseFlag"":0,""Bolt_AlertFlag"":0}")]
        public string GoodSettings {
            get {
                return ((string)(this["GoodSettings"]));
            }
            set {
                this["GoodSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""Bolt_date"":"""",""Bolt_time"":"""",""TempUnits"":""C"",""WindSpeedUnits"":""K"",""Bolt_SkyTemp"":10,""Bolt_Temp"":10,""Bolt_SensorTemp"":10,""Bolt_WindSpeed"":20,""Bolt_Hum"":70,""Bolt_DewPoint"":-100,""Bolt_Heater"":30,""Bolt_RainFlag"":2,""Bolt_WetFlag"":2,""Bolt_SinceLastMeasure"":0,""Bolt_now"":0,""Bolt_CloudCond"":3,""Bolt_WindCond"":3,""Bolt_RainCond"":3,""Bolt_DaylighCond"":1,""Bolt_RoofCloseFlag"":1,""Bolt_AlertFlag"":1}")]
        public string BadSettings {
            get {
                return ((string)(this["BadSettings"]));
            }
            set {
                this["BadSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseBoltwoodLogic {
            get {
                return ((bool)(this["UseBoltwoodLogic"]));
            }
            set {
                this["UseBoltwoodLogic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("useLocale")]
        public string decimalPoint {
            get {
                return ((string)(this["decimalPoint"]));
            }
            set {
                this["decimalPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
    }
}
